version: 2.1

# Resources: https://github.com/CircleCI-Public/android-testing-circleci-examples/blob/master/.circleci/config.yml
# and: https://circleci.com/blog/building-android-on-circleci/
# and: https://circleci.com/developer/orbs/orb/circleci/android#commands-start-emulator

orbs:
  android: circleci/android@1.0.3
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release-build:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: | # Here we are building the release variant using assembleRelease
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

# We created a workflow called test-and-build. When a commit it pushed, it will run all unit test
# and instrumented test on that branch. When the master branch has been changed, it will run another
# instrumented test on master but this time, it will run the instrumented tests on android 23 -> 30 commands:
# there generate release build if all tests on master passes.
workflows:
  test-and-build:
    jobs:
      - unit-test
      - android/run-ui-tests
      - release-build:
          requires:
            - unit-test
            - android/run-ui-tests
          filters:
            branches:
              only: master # Commits to master branch